# This file contains the configuration for different models used in the project.
# Each model is categorized into different sections based on its training type.
#
# To add a new model, copy the template below and fill in the details.
# Template:
# <model_name>:
#   engine: <engine_name>
#   model: <path_to_model_file>
#   preprocessing: <preprocessing_method>
#   input_width: <input_image_width>
#   input_height: <input_image_height>
# Example:
# InsectArmageddon:
#   engine: Standardized
#   model: models/ia.pth
#   preprocessing: torch
#   input_width: 2688
#   input_height: 1536
#
# Note: Ensure that the model paths are correct and the preprocessing methods
# are compatible with the models.
# The values "preprocessing", "engine", "input_width" and "input_height" are
# optional and default to:
#   preprocessing: torch
#   engine: Standardized
#   input_width: 3200
#   input_height: 1792

cover-trained:
  #  <Your Model Name>:
  #    engine: Standardized
  #    model: models/<your_model_filename>.pth
  #    preprocessing: torch
  #    input_width: 2688
  #    input_height: 1536


zero-shot:
  #  <Your Model Name>:
  #    engine: Standardized
  #    model: models/<your_model_filename>.pth
  #    preprocessing: torch
  #    input_width: 2688
  #    input_height: 1536